# Generated by Django 5.0.4 on 2024-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_restaurant_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_img',
            field=models.ImageField(blank=True, upload_to='customer_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_img',
            field=models.ImageField(blank=True, upload_to='resto_images'),
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_img',
            field=models.ImageField(blank=True, upload_to='rider_images'),
        ),
    ]
