# Generated by Django 5.0.4 on 2024-05-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_customer_img_restaurant_restaurant_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_img',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_img',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rider_img',
        ),
    ]
