# Generated by Django 5.0.4 on 2024-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customer_customer_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resto_images'),
        ),
        migrations.AddField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_images'),
        ),
    ]
