# Generated by Django 5.0.4 on 2024-05-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer_image_restaurant_image_rider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='image',
        ),
    ]
