# Generated by Django 5.0.4 on 2024-05-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customadmin_user_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAdmin',
            new_name='Custom_Admin',
        ),
    ]
