# Generated by Django 5.0.4 on 2024-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_restaurant_resto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_images/'),
        ),
    ]
