# Generated by Django 5.0.4 on 2024-05-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='rider',
        ),
    ]
