# Generated by Django 5.0.4 on 2024-05-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_is_admin_delete_custom_admin'),
        ('transactions', '0007_remove_cartitem_restaurant_remove_cartitem_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.restaurant'),
        ),
    ]
