# Generated by Django 5.0.4 on 2024-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
