# Generated by Django 5.0.4 on 2024-05-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_order_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.cartitem'),
        ),
    ]
