# Generated by Django 5.0.4 on 2024-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
