# Generated by Django 5.0.4 on 2024-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_order_delivery_fee_remove_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
