# Generated by Django 5.0.4 on 2024-05-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_code',
        ),
    ]
