# Generated by Django 5.0.4 on 2024-05-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_is_admin_delete_custom_admin'),
        ('transactions', '0023_remove_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
