# Generated by Django 5.0.4 on 2024-05-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.menuitem'),
        ),
    ]
