# Generated by Django 5.0.4 on 2024-05-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_menuitem_restaurant_payment_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartItem',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
