# Generated by Django 5.0.4 on 2024-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mop',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'Gcash'), ('PAYPAL', 'PayPal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
