# Generated by Django 5.0.4 on 2024-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_remove_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
