# Generated by Django 5.0.4 on 2024-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_remove_order_note_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(null=True),
        ),
    ]
