# Generated by Django 5.0.4 on 2024-05-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_address',
        ),
    ]
