# Generated by Django 5.0.4 on 2024-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_remove_order_current_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
