# Generated by Django 5.0.4 on 2024-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_payment_current_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rider',
        ),
    ]
